export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          avatar_url: string | null;
          phone: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          avatar_url?: string | null;
          phone?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          phone?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      organizations: {
        Row: {
          id: string;
          name: string;
          legal_name: string | null;
          email: string | null;
          phone: string | null;
          website: string | null;
          logo_url: string | null;
          address: string | null;
          city: string | null;
          state: string | null;
          postal_code: string | null;
          country: string | null;
          gstin: string | null;
          pan: string | null;
          currency: string;
          timezone: string;
          date_format: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          legal_name?: string | null;
          email?: string | null;
          phone?: string | null;
          website?: string | null;
          logo_url?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          country?: string | null;
          gstin?: string | null;
          pan?: string | null;
          currency?: string;
          timezone?: string;
          date_format?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          legal_name?: string | null;
          email?: string | null;
          phone?: string | null;
          website?: string | null;
          logo_url?: string | null;
          address?: string | null;
          city?: string | null;
          state?: string | null;
          postal_code?: string | null;
          country?: string | null;
          gstin?: string | null;
          pan?: string | null;
          currency?: string;
          timezone?: string;
          date_format?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      organization_members: {
        Row: {
          id: string;
          organization_id: string;
          user_id: string;
          role: 'owner' | 'admin' | 'accountant' | 'staff' | 'viewer';
          status: 'active' | 'invited' | 'suspended';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          user_id: string;
          role: 'owner' | 'admin' | 'accountant' | 'staff' | 'viewer';
          status?: 'active' | 'invited' | 'suspended';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          user_id?: string;
          role?: 'owner' | 'admin' | 'accountant' | 'staff' | 'viewer';
          status?: 'active' | 'invited' | 'suspended';
          created_at?: string;
          updated_at?: string;
        };
      };
      customers: {
        Row: {
          id: string;
          organization_id: string;
          customer_number: string;
          customer_type: string;
          company_name: string;
          display_name: string;
          contact_person: string | null;
          email: string | null;
          phone: string | null;
          tax_type: string | null;
          gstin: string | null;
          pan: string | null;
          payment_terms: string | null;
          billing_address: Json;
          shipping_address: Json;
          same_as_billing_address: boolean;
          notes: string | null;
          is_active: boolean;
          total_invoiced: number;
          paid: number;
          outstanding: number;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          customer_number: string;
          customer_type?: string;
          company_name: string;
          display_name: string;
          contact_person?: string | null;
          email?: string | null;
          phone?: string | null;
          tax_type?: string | null;
          gstin?: string | null;
          pan?: string | null;
          payment_terms?: string | null;
          billing_address?: Json;
          shipping_address?: Json;
          same_as_billing_address?: boolean;
          notes?: string | null;
          is_active?: boolean;
          total_invoiced?: number;
          paid?: number;
          outstanding?: number;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          customer_number?: string;
          customer_type?: string;
          company_name?: string;
          display_name?: string;
          contact_person?: string | null;
          email?: string | null;
          phone?: string | null;
          tax_type?: string | null;
          gstin?: string | null;
          pan?: string | null;
          payment_terms?: string | null;
          billing_address?: Json;
          shipping_address?: Json;
          same_as_billing_address?: boolean;
          notes?: string | null;
          is_active?: boolean;
          total_invoiced?: number;
          paid?: number;
          outstanding?: number;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
      };
      items: {
        Row: {
          id: string;
          organization_id: string;
          item_code: string;
          name: string;
          sku: string | null;
          type: string;
          description: string | null;
          category: string;
          unit: string;
          selling_price: number;
          cost_price: number | null;
          tax_type: string | null;
          tax_rate: number | null;
          hsn_sac_code: string | null;
          discount_rate: number | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          item_code: string;
          name: string;
          sku?: string | null;
          type?: string;
          description?: string | null;
          category?: string;
          unit?: string;
          selling_price?: number;
          cost_price?: number | null;
          tax_type?: string | null;
          tax_rate?: number | null;
          hsn_sac_code?: string | null;
          discount_rate?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          item_code?: string;
          name?: string;
          sku?: string | null;
          type?: string;
          description?: string | null;
          category?: string;
          unit?: string;
          selling_price?: number;
          cost_price?: number | null;
          tax_type?: string | null;
          tax_rate?: number | null;
          hsn_sac_code?: string | null;
          discount_rate?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
      };
      quotes: {
        Row: {
          id: string;
          organization_id: string;
          customer_id: string;
          quote_number: string;
          quote_date: string;
          valid_until: string;
          status: 'draft' | 'sent' | 'accepted' | 'rejected' | 'expired' | 'converted';
          subtotal: number;
          discount: number;
          tax: number;
          total: number;
          notes: string | null;
          terms: string | null;
          converted_to_invoice_id: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          customer_id: string;
          quote_number: string;
          quote_date?: string;
          valid_until: string;
          status?: 'draft' | 'sent' | 'accepted' | 'rejected' | 'expired' | 'converted';
          subtotal?: number;
          discount?: number;
          tax?: number;
          total?: number;
          notes?: string | null;
          terms?: string | null;
          converted_to_invoice_id?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          customer_id?: string;
          quote_number?: string;
          quote_date?: string;
          valid_until?: string;
          status?: 'draft' | 'sent' | 'accepted' | 'rejected' | 'expired' | 'converted';
          subtotal?: number;
          discount?: number;
          tax?: number;
          total?: number;
          notes?: string | null;
          terms?: string | null;
          converted_to_invoice_id?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
      };
      quote_items: {
        Row: {
          id: string;
          organization_id: string;
          quote_id: string;
          item_id: string | null;
          description: string;
          quantity: number;
          unit_price: number;
          discount: number;
          tax_rate: number;
          tax_amount: number;
          line_total: number;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          quote_id: string;
          item_id?: string | null;
          description: string;
          quantity?: number;
          unit_price?: number;
          discount?: number;
          tax_rate?: number;
          tax_amount?: number;
          line_total?: number;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          quote_id?: string;
          item_id?: string | null;
          description?: string;
          quantity?: number;
          unit_price?: number;
          discount?: number;
          tax_rate?: number;
          tax_amount?: number;
          line_total?: number;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      invoices: {
        Row: {
          id: string;
          organization_id: string;
          customer_id: string;
          quote_id: string | null;
          invoice_number: string;
          invoice_date: string;
          due_date: string;
          status: 'draft' | 'sent' | 'partially_paid' | 'paid' | 'overdue' | 'cancelled';
          subtotal: number;
          discount: number;
          tax: number;
          total: number;
          amount_paid: number;
          balance_due: number;
          notes: string | null;
          terms: string | null;
          template_id: string | null;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          customer_id: string;
          quote_id?: string | null;
          invoice_number: string;
          invoice_date?: string;
          due_date: string;
          status?: 'draft' | 'sent' | 'partially_paid' | 'paid' | 'overdue' | 'cancelled';
          subtotal?: number;
          discount?: number;
          tax?: number;
          total?: number;
          amount_paid?: number;
          balance_due?: number;
          notes?: string | null;
          terms?: string | null;
          template_id?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          customer_id?: string;
          quote_id?: string | null;
          invoice_number?: string;
          invoice_date?: string;
          due_date?: string;
          status?: 'draft' | 'sent' | 'partially_paid' | 'paid' | 'overdue' | 'cancelled';
          subtotal?: number;
          discount?: number;
          tax?: number;
          total?: number;
          amount_paid?: number;
          balance_due?: number;
          notes?: string | null;
          terms?: string | null;
          template_id?: string | null;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
      };
      invoice_items: {
        Row: {
          id: string;
          organization_id: string;
          invoice_id: string;
          item_id: string | null;
          description: string;
          quantity: number;
          unit_price: number;
          discount: number;
          tax_rate: number;
          tax_amount: number;
          line_total: number;
          sort_order: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          invoice_id: string;
          item_id?: string | null;
          description: string;
          quantity?: number;
          unit_price?: number;
          discount?: number;
          tax_rate?: number;
          tax_amount?: number;
          line_total?: number;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          organization_id?: string;
          invoice_id?: string;
          item_id?: string | null;
          description?: string;
          quantity?: number;
          unit_price?: number;
          discount?: number;
          tax_rate?: number;
          tax_amount?: number;
          line_total?: number;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      organization_counters: {
        Row: {
          organization_id: string;
          entity_type: string;
          current_value: number;
          prefix: string;
          updated_at: string;
        };
        Insert: {
          organization_id: string;
          entity_type: string;
          current_value?: number;
          prefix?: string;
          updated_at?: string;
        };
        Update: {
          organization_id?: string;
          entity_type?: string;
          current_value?: number;
          prefix?: string;
          updated_at?: string;
        };
      };
      payments: {
        Row: {
          id: string;
          organization_id: string;
          invoice_id: string;
          customer_id: string;
          payment_number: string;
          amount: number;
          payment_date: string;
          payment_method: string;
          reference_number: string | null;
          notes: string | null;
          status: string;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          invoice_id: string;
          customer_id: string;
          payment_number: string;
          amount: number;
          payment_date?: string;
          payment_method: string;
          reference_number?: string | null;
          notes?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          invoice_id?: string;
          customer_id?: string;
          payment_number?: string;
          amount?: number;
          payment_date?: string;
          payment_method?: string;
          reference_number?: string | null;
          notes?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
      };
      expenses: {
        Row: {
          id: string;
          organization_id: string;
          expense_number: string;
          category: string;
          description: string;
          amount: number;
          expense_date: string;
          payment_method: string;
          vendor: string | null;
          reference_number: string | null;
          notes: string | null;
          status: string;
          created_at: string;
          updated_at: string;
          created_by: string | null;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          expense_number?: string;
          category: string;
          description: string;
          amount: number;
          expense_date?: string;
          payment_method?: string;
          vendor?: string | null;
          reference_number?: string | null;
          notes?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          organization_id?: string;
          expense_number?: string;
          category?: string;
          description?: string;
          amount?: number;
          expense_date?: string;
          payment_method?: string;
          vendor?: string | null;
          reference_number?: string | null;
          notes?: string | null;
          status?: string;
          created_at?: string;
          updated_at?: string;
          created_by?: string | null;
          updated_by?: string | null;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      is_organization_member: {
        Args: { org_id: string };
        Returns: boolean;
      };
      get_user_organization_role: {
        Args: { org_id: string };
        Returns: string;
      };
      generate_next_number: {
        Args: { _org_id: string; _entity_type: string; _default_prefix: string };
        Returns: string;
      };
    };
    Enums: {
      [_ in never]: never;
    };
  };
}

